flowber_group_create:
    path:     /nouveau
    defaults: { _controller: FlowberGroupBundle:Group:createGroup }

flowber_group_search:
    path:     /rechercher
    defaults: { _controller: FlowberGroupBundle:Group:groupSearch }

flowber_group_homepage:
    path:     /{id}
    defaults: { _controller: FlowberGroupBundle:Group:group }
    requirements:
        id: \d+
    
flowber_group_galleries:
    path:     /{id}/galleries
    defaults: { _controller: FlowberGroupBundle:Group:groupGalleries }
    requirements:
        id: \d+
    
flowber_group_members:
    path:     /{id}/membres
    defaults: { _controller: FlowberGroupBundle:Group:groupMembers }
    requirements:
        id: \d+
    
flowber_group_events:
    path:     /{id}/sorties
    defaults: { _controller: FlowberGroupBundle:Group:groupEvents }
    requirements:
        id: \d+
   
flowber_all_group_homepage:
    path:     /tous_mes_groupes
    defaults: { _controller: FlowberGroupBundle:Group:AllGroups }
