flowber_group_research:
    path:     /rechercher
    defaults: { _controller: FlowberGroupBundle:Group:getSearch }

flowber_group_create:
    path:     /nouveau
    defaults: { _controller: FlowberGroupBundle:Group:getCreateGroup }

flowber_groups_homepage:
    path:     /{circleId}
    defaults: { _controller: FlowberGroupBundle:Group:getGroup }
    requirements:
        id: \d+

flowber_group_galleries:
    path:     /{id}/galleries
    defaults: { _controller: FlowberGroupBundle:Group:getGroupGalleries }
    requirements:
        id: \d+
        
flowber_group_gallery:
    path:     /{circleId}/gallery/{galleryId}
    defaults: { _controller: FlowberGroupBundle:Group:getGroupGallery }
    requirements:
        circleId: \d+
        galleryId: \d+
    
flowber_group_members:
    path:     /{id}/membres
    defaults: { _controller: FlowberGroupBundle:Group:getGroupMembers }
    requirements:
        id: \d+
    
flowber_group_events:
    path:     /{id}/sorties
    defaults: { _controller: FlowberGroupBundle:Group:getGroupEvents }
    requirements:
        id: \d+
   
flowber_all_group:
    path:     /{id}/tous_mes_groupes
    defaults: { _controller: FlowberGroupBundle:Group:getAllGroups }

flowber_groups_edit:
    path:     /{circleId}/edit
    defaults: { _controller: FlowberGroupBundle:Group:editGroup }
    requirements:
        id: \d+