flowber_group_homepage:
    path:     /groupe/{id}
    defaults: { _controller: FlowberGroupBundle:Group:getGroup }
    
flowber_group_galleries:
    path:     /groupe/{id}/galleries
    defaults: { _controller: FlowberGroupBundle:Group:getGroupGalleries }
    
flowber_group_members:
    path:     /groupe/{id}/membres
    defaults: { _controller: FlowberGroupBundle:Group:getGroupMembers }
    
flowber_group_events:
    path:     /groupe/{id}/sorties
    defaults: { _controller: FlowberGroupBundle:Group:getGroupEvents }

flowber_create_group_homepage:
    path:     /nouveau_groupe
    defaults: { _controller: FlowberGroupBundle:Group:getCreateGroup }
    
flowber_all_group_homepage:
    path:     /tous_mes_groupes
    defaults: { _controller: FlowberGroupBundle:Group:getAllGroups }
