#src/Flowber/GroupBundle/Resources/config/routing_rest.yml
groups : 
  type: rest
  resource:     "FlowberGroupBundle:GroupRest" #Flowber\GroupBundle\Controller\GroupRestController
  name_prefix:  api_