add_comment_post:
    pattern:  /comment/{post_id}
    defaults: { _controller: FlowberPostBundle:Post:addCommentGroup }
    requirements:
        _method:  POST
        post_id: \d+
        
add_comment_post_event:
    pattern:  /comment_event/{post_id}
    defaults: { _controller: FlowberPostBundle:Post:addCommentEvent }
    requirements:
        _method:  POST
        post_id: \d+
        
add_post:
    pattern:  /post/{group_id}
    defaults: { _controller: FlowberPostBundle:Post:addPostGroup }
    requirements:
        _method:  POST
        group_id: \d+
        
add_post_event:
    pattern:  /post_event/{event_id}
    defaults: { _controller: FlowberPostBundle:Post:addPostEvent }
    requirements:
        _method:  POST
        group_id: \d+
        
add_post_with_event:
    pattern:  /postWithEvent/{group_id}
    defaults: { _controller: FlowberPostBundle:Post:addPostWithEvent }
    requirements:
        _method:  POST
        group_id: \d+
        
delete_post:
    pattern:  /supprimer_poste #/{post_id}
    defaults: { _controller: FlowberPostBundle:Post:deletePost }
#    requirements:
#        group_id: \d+

delete_comment:
    pattern:  /supprimer_commentaire/{comment_id}
    defaults: { _controller: FlowberPostBundle:Post:deleteComment }
    requirements:
        group_id: \d+