flowber_request:
    path:     /requete
    defaults: { _controller: FlowberCircleBundle:Circle:getRequestPage }
    
flowber_notification:
    path:     /notification
    defaults: { _controller: FlowberCircleBundle:Circle:getNotificationPage }