<?php

namespace Flowber\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Flowber\EventBundle\Entity\Event;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function getInfosEvent($id){
        
        $query = $this->_em->createQuery(''
                . 'SELECT a.title, a.subtitle, a.eventDate, a.description, '
                . 'c.name, c.address, c.city, c.zipcode, c.coordinate, b.firstname, b.surname,'
                . 'd.file as profilePic, e.file as coverPic '
                . 'FROM FlowberEventBundle:Event a '
                . 'LEFT JOIN FlowberUserBundle:PostalAddress c  WITH a.postalAddress = c '
                . 'LEFT JOIN FlowberUserBundle:User b WITH a.createdBy = b '
                . 'LEFT JOIN FlowberGalleryBundle:Photo d WITH a.profilePicture = d '
                . 'LEFT JOIN FlowberGalleryBundle:Photo e WITH a.coverPicture = e '
                . 'WHERE a.id = :id');
        $query->setParameter('id', $id);
        
        return $query->getSingleResult();
    }
}
