<?php

namespace Flowber\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParticipantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantsRepository extends EntityRepository
{
}
