flowber_privatemessage_received_homepage:
    path:     /recus
    defaults: { _controller: FlowberPrivateMessageBundle:PrivateMessage:getAllMessagesReceived }

flowber_privatemessage_sent_homepage:
    path:     /envoyes
    defaults: { _controller: FlowberPrivateMessageBundle:PrivateMessage:getAllMessagesSent }

flowber_privatemessage_deleted_homepage:
    path:     /mesages_supprimes
    defaults: { _controller: FlowberPrivateMessageBundle:PrivateMessage:getAllMessagesDeleted }

flowber_privatemessage_send_one_homepage:
    path:     /mesage_send/{id}
    defaults: { _controller: FlowberPrivateMessageBundle:PrivateMessage:getMessageSend }
    
flowber_privatemessage_deleted_one_homepage:
    path:     /mesage_deleted/{id}
    defaults: { _controller: FlowberPrivateMessageBundle:PrivateMessage:getMessageDeleted }
    
flowber_delete_message:
    path:     /supprimer_message/{id}/{type}
    defaults: { _controller: FlowberPrivateMessageBundle:PrivateMessage:deleteMessage }

flowber_read_message:
    path:     /lu_non_lu_message/{id}
    defaults: { _controller: FlowberPrivateMessageBundle:PrivateMessage:readMessage }
    
mp_sent :
    path:     /envoye/{id}
    defaults: { _controller: FlowberPrivateMessageBundle:PrivateMessage:getMessageSent}

mp_sentDeleted :
    path:     /envoyeD/{id}
    defaults: { _controller: FlowberPrivateMessageBundle:PrivateMessage:getMessageSentDeleted}

mp_received :
    path:     /recu/{id}
    defaults: { _controller: FlowberPrivateMessageBundle:PrivateMessage:getMessageReceived}

mp_receivedDeleted :
    path:     /recuD/{id}
    defaults: { _controller: FlowberPrivateMessageBundle:PrivateMessage:getMessageReceivedDeleted}