#src/Flowber/LikesBundle/Resources/config/routing_rest.yml
like : 
    type: rest
    resource:     "FlowberPrivateMessageBundle:PrivateMessageRest"
    name_prefix:  api_
    options:
        expose: true
        