services:
    flowber_privateMessage.privateMessage:
        class: Flowber\PrivateMessageBundle\Manager\PrivateMessageManager
        arguments: [@doctrine.orm.entity_manager, @flowber_circle.circle] 