<?php

namespace Flowber\CircleBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Flowber\UserBundle\Entity\User;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    public function getInfosNotifications($circleId){  
        $sql = "SELECT a.id, b.id as notifReceivedId, a.sender_id, a.message, a.pageName, a.pageRoute, a.pageId, b.statut, a.creationDate, b.statut "
                . "FROM notification a, notification_receiver b "
                . "WHERE b.receiver = ".$circleId." AND b.notification_id=a.id "
                . "ORDER BY a.creationDate desc";
       
        $rsm = new ResultSetMapping;
        $rsm->addScalarResult('sender_id', 'senderId');
        $rsm->addScalarResult('id', 'requestId');
        $rsm->addScalarResult('notifReceivedId', 'notifReceivedId');
        $rsm->addScalarResult('statut', 'statut');
        $rsm->addScalarResult('message', 'message');
        $rsm->addScalarResult('pageName', 'pageName');
        $rsm->addScalarResult('pageRoute', 'pageRoute');
        $rsm->addScalarResult('pageId', 'pageId');
        $rsm->addScalarResult('statut', 'statut');
        $rsm->addScalarResult('creationDate', 'creationDate');
        
        return $this->getEntityManager()->createNativeQuery($sql, $rsm)->getResult();    
    }
    
    public function getNumberNotifications($circleId){  
        $sql = "SELECT b.id "
                . "FROM notification_receiver b "
                . "WHERE b.receiver = ".$circleId." AND b.statut='received'";
       
        $rsm = new ResultSetMapping;
        $rsm->addScalarResult('id', 'id');
       
        return count($this->getEntityManager()->createNativeQuery($sql, $rsm)->getResult());    
    }
    
}
