<?php

namespace Flowber\CircleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationReceiverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationReceiverRepository extends EntityRepository
{
}
