<?php

namespace Flowber\CircleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubscribersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscribersRepository extends EntityRepository
{
}
