flowber_event_homepage:
    path:     /sortie/{id}
    defaults: { _controller: FlowberEventBundle:Event:event }

flowber_create_event_homepage:
    path:     /nouvelle_sortie
    defaults: { _controller: FlowberEventBundle:Event:createEvent }

flowber_all_event_homepage:
    path:     /toutes_mes_sorties
    defaults: { _controller: FlowberEventBundle:Event:AllEvent }
