flowber_event_homepage:
    path:     /sortie/{circleId}
    defaults: { _controller: FlowberEventBundle:Event:getEventPage }
    requirements:
        id : \d+
    
flowber_event_participants:
    path:     /sortie/{id}/participants
    defaults: { _controller: FlowberEventBundle:Event:getEventParticipantsPage }
    
flowber_event_gallery:
    path:     /sortie/{id}/gallerie
    defaults: { _controller: FlowberEventBundle:Event:getEventGalleryPage }

flowber_create_event_homepage:
    path:     /nouvelle_sortie
    defaults: { _controller: FlowberEventBundle:Event:getCreateEvent }

flowber_event_edit:
    path:     /{circleId}/edit
    defaults: { _controller: FlowberEventBundle:Event:getEditEvent }

flowber_all_event_homepage:
    path:     /toutes_mes_sorties
    defaults: { _controller: FlowberEventBundle:Event:getAllEventsPage }

flowber_add_participant:
    path:     /{id}/addParticipant
    defaults: { _controller: FlowberEventBundle:Participant:addParticipant }
    requirements:
        id: \d+