flowber_event_homepage:
    path:     /sortie/{circleId}
    defaults: { _controller: FlowberEventBundle:Event:getEventPage }
    requirements:
        id : \d+
    
flowber_event_participants:
    path:     /{id}/participants
    defaults: { _controller: FlowberEventBundle:Event:getParticipantsPage }
    
flowber_event_galleries:
    path:     /{id}/galleries
    defaults: { _controller: FlowberEventBundle:Event:getEventGalleries }
    
flowber_event_gallery:
    path:     /{circleId}/gallery/{galleryId}
    defaults: { _controller: FlowberEventBundle:Event:getEventGallery }
    requirements:
        circleId: \d+
        galleryId: \d+

flowber_create_event_homepage:
    path:     /nouvelle_sortie
    defaults: { _controller: FlowberEventBundle:Event:getCreateEvent }

flowber_event_edit:
    path:     /{circleId}/edit
    defaults: { _controller: FlowberEventBundle:Event:getEditEvent }

flowber_all_event_homepage:
    path:     /{id}/toutes_mes_sorties
    defaults: { _controller: FlowberEventBundle:Event:getAllEventsPage }
    
flowber_event_search:
    path:     /rechercher_sortie
    defaults: { _controller: FlowberEventBundle:Event:getEventSearchPage }
    
flowber_add_participant:
    path:     /{id}/addParticipant
    defaults: { _controller: FlowberEventBundle:Participant:addParticipant }
    requirements:
        id: \d+