#app/routing_rest.yml
rest_group : 
  type : rest
  resource: "@FlowberGroupBundle/Resources/config/routing_rest.yml"
  
rest_post : 
  type : rest
  resource: "@FlowberPostBundle/Resources/config/routing_rest.yml"
  
rest_likes : 
  type : rest
  resource: "@FlowberLikeBundle/Resources/config/routing_rest.yml"
  
rest_private_message : 
  type : rest
  resource: "@FlowberPrivateMessageBundle/Resources/config/routing_rest.yml"
  
rest_circle : 
  type : rest
  resource: "@FlowberCircleBundle/Resources/config/routing_rest.yml"
  
rest_profile : 
  type : rest
  resource: "@FlowberProfileBundle/Resources/config/routing_rest.yml"