fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

flowber_notification:
    resource: "@FlowberNotificationBundle/Resources/config/routing.yml"
    prefix:   /notification

flowber_like:
    resource: "@FlowberLikeBundle/Resources/config/routing.yml"
    prefix:   /like

flowber_post:
    resource: "@FlowberPostBundle/Resources/config/routing.yml"
    prefix:   /post

flowber_group:
    resource: "@FlowberGroupBundle/Resources/config/routing.yml"
    prefix:   /groupe

flowber_event:
    resource: "@FlowberEventBundle/Resources/config/routing.yml"
    prefix:   /sortie

flowber_private_message:
    resource: "@FlowberPrivateMessageBundle/Resources/config/routing.yml"
    prefix:   /messages-prives

flowber_gallery:
    resource: "@FlowberGalleryBundle/Resources/config/routing.yml"
    prefix:   /gallerie

flowber_profile:
    resource: "@FlowberProfileBundle/Resources/config/routing.yml"
    prefix:   /profil

flowber_front_office:
    resource: "@FlowberFrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /

flowber_user:
    resource: "@FlowberUserBundle/Resources/config/routing.yml"
    prefix:   /user
    
#http://www.foulquier.info/tutoriaux/mise-en-place-d-une-api-rest-avec-fosrestbundle-dans-symfony-2
flowber_post_anno:
    resource: "@FlowberPostBundle/Controller/"
    type:     annotation
    prefix:   /

#REST 
rest : 
    type : rest 
    resource : "routing_rest.yml"
    prefix : /api

wybe_front_office:
    resource: "@WybeFrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /wybe

app:
    resource: "@AppBundle/Controller/"
    type:     annotation