flowber_front_office:
    resource: "@FlowberFrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /

flowber_user:
    resource: "@FlowberUserBundle/Resources/config/routing.yml"
    prefix:   /user

wybe_front_office:
    resource: "@WybeFrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /wybe

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
