flowber_event:
    resource: "@FlowberEventBundle/Resources/config/routing.yml"
    prefix:   /

flowber_private_message:
    resource: "@FlowberPrivateMessageBundle/Resources/config/routing.yml"
    prefix:   /

flowber_gallery:
    resource: "@FlowberGalleryBundle/Resources/config/routing.yml"
    prefix:   /gallerie

flowber_profile:
    resource: "@FlowberProfileBundle/Resources/config/routing.yml"
    prefix:   /profil

flowber_front_office:
    resource: "@FlowberFrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /

flowber_user:
    resource: "@FlowberUserBundle/Resources/config/routing.yml"
    prefix:   /user

wybe_front_office:
    resource: "@WybeFrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /wybe

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
