security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle: # main:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: true
#            provider:  main
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # was commented before
                login_path: flowber_user_signin_homepage # fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path: true  
                default_target_path: flowber_front_office_redirect
            logout:
                path:   fos_user_security_logout
                target: flowber_user_signin_homepage
            remember_me:
                key:        %secret% # %secret% est un paramètre de parameters.yml
                
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
