like_post_group:
    pattern:  /like_post_group/{post_id}
    defaults: { _controller: FlowberLikeBundle:Like:likePostGroup }
    requirements:
        group_id: \d+
        
unlike_post_group:
    pattern:  /unlike_post_group/{like_id}/{post_id}
    defaults: { _controller: FlowberLikeBundle:Like:unlikePostGroup }
    requirements:
        group_id: \d+
        
like_post_event:
    pattern:  /like_post_event/{post_id}
    defaults: { _controller: FlowberLikeBundle:Like:likePostEvent }
    requirements:
        group_id: \d+

unlike_post_event:
    pattern:  /unlike_post_event/{like_id}/{post_id}
    defaults: { _controller: FlowberLikeBundle:Like:unlikePostEvent }
    requirements:
        group_id: \d+