<?php

namespace Flowber\GroupBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository
{
    public function getInfosGroup($id){  
        $query = $this->_em->createQuery(''
                . 'SELECT groups.id, groups.title, groups.subtitle, groups.description, '
                . 'concat(concat(user.firstname, :espace), user.surname) as createdBy '
                . 'FROM FlowberGroupBundle:Groups groups '
                . 'LEFT JOIN FlowberUserBundle:User user WITH groups.createdBy = user '
                . 'WHERE groups.id = :id');
        $query->setParameter('id', $id);
        $query->setParameter('espace', ' ');
       
        return $query->getSingleResult();
    }
}
