<?php

namespace Flowber\GalleryBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Flowber\GalleryBundle\Entity\Photo;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository
{
    public function setDeleted(Photo $photo, $choice){
        $photoId = $photo->getId();
        
        $qb = $this->_em->createQueryBuilder();
        
        $datetime = new \Datetime();
        $now = $datetime->format("Y-m-d H:i:s");
        
        $query = $qb->update('FlowberGalleryBundle:Photo', 'a')
            ->set('a.deleted', '?1')
            ->set('a.deleteDate', ':now')
            ->where('a.id = :id')
            ->setParameter('id', $photoId)
            ->setParameter('now', $now)
            ->setParameter(1, $choice)
            ->getQuery();
        
        return $query->execute();
    }
}
