<?php

namespace Flowber\PostBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    
    public function getPostFromGroup($groupId){
        $qb = $this->_em->createQueryBuilder();
        
        $qb->select('a')
            ->from('FlowberPostBundle:Post', 'a')
            ->where('a.groups = :groupId')
            ->setParameter('groupId', $groupId)          
            ->andWhere('a.statut != :statut')
            ->setParameter('statut', '0')
            ->orderBy('a.creationDate', 'DESC');
        
        return $qb->getQuery()
                  ->getResult();
    }

    public function getPostFromEvent($eventId){
        $qb = $this->_em->createQueryBuilder();
        
        $qb->select('a')
            ->from('FlowberPostBundle:Post', 'a')
            ->where('a.event = :eventId')
            ->setParameter('eventId', $eventId)          
            ->andWhere('a.statut != :statut')
            ->setParameter('statut', '0')
            ->orderBy('a.creationDate', 'DESC');
        
        return $qb->getQuery()
                  ->getResult();
    }
    
    public function getCommentFromPost($postId){
        $qb = $this->_em->createQueryBuilder();
        
        $qb->select('a')
            ->from('FlowberPostBundle:Comment', 'a')
            ->where('a.post = :postId')
            ->setParameter('postId', $postId)          
            ->andWhere('a.statut != :statut')
            ->setParameter('statut', '0')
            ->orderBy('a.creationDate', 'DESC');
        
        return $qb->getQuery()
                  ->getResult();
    }
}