<?php

namespace Flowber\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostalAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostalAddressRepository extends EntityRepository
{
}
