<?php

namespace Flowber\NotificationBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Flowber\UserBundle\Entity\User;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    /*
     * Récupère les notifications d'un utilisateur
     * Return entities notifications
     * Order by creationDate desc 
     * limit 10
     */    
    public function getUserNotification(User $user){
        $qb = $this->_em->createQueryBuilder();
        
        return $qb->getQuery()
                  ->getResult();
    }
}
