<?php

namespace Flowber\PrivateMessageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReceiverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceiverRepository extends EntityRepository
{
}
