<?php

namespace Flowber\ProfileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HobbyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HobbyRepository extends EntityRepository
{
}
