<?php

namespace Flowber\ProfileBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Flowber\UserBundle\Entity\User;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends EntityRepository
{
    /*
     * Récupère la phrase d'accroche et la description
     * Return subtitle, job, description, creationDate
     */
    public function getUserInfoForProfile($id){
        
    }
    
    /*
     * Récupère les hobbies de l'utilisateur
     * Return title, percent, description
     */
    public function getUserHobbies(User $user){
        
    }
  
}
