flowber_profile_homepage:
    path:     /profil
    defaults: { _controller: FlowberProfileBundle:Default:getProfile }

flowber_profile_modif_homepage:
    path:     /profil/modifier
    defaults: { _controller: FlowberProfileBundle:Default:getProfileModifier }
