flowber_profile:
    path:     /profil
    defaults: { _controller: FlowberProfileBundle:Default:getProfile }

flowber_profile_edit:
    path:     /profil/modifier
    defaults: { _controller: FlowberProfileBundle:Default:getProfileModifier }
