#src/Flowber/ProfileBundle/Resources/config/routing_rest.yml
profile : 
    type: rest
    resource:     "FlowberProfileBundle:ProfileRest"
    name_prefix:  api_
    options:
        expose: true      