flowber_user_search:
    path: /search
    defaults: { _controller: FlowberProfileBundle:Profile:getSearchUserPage }

flowber_profile_homepage:
    path:     /{circleId}
    defaults: { _controller: FlowberProfileBundle:Profile:getUserProfile }
    requirements:
        circleId: \d+

flowber_profile_edit:
    path:     /{circleId}/edit
    defaults: { _controller: FlowberProfileBundle:Profile:getEditProfile }

flowber_profile_current_user:
    path: /me
    defaults: { _controller: FlowberProfileBundle:Profile:getCurrentUserProfile }
    
flowber_profile_galleries:
    path:     /{id}
    defaults: { _controller: FlowberProfileBundle:Profile:getUserProfile }
    
flowber_profile_gallery:
    path:     /{circleId}/gallery/{galleryId}
    defaults: { _controller: FlowberProfileBundle:Profile:getProfileGallery }
    requirements:
        circleId: \d+
        galleryId: \d+