flowber_current_user_profile:
    path:     /mon-profil
    defaults: { _controller: FlowberProfileBundle:Default:getCurrentUserProfile }

flowber_profile_edit:
    path:     /mon-profil/modifier
    defaults: { _controller: FlowberProfileBundle:Default:getProfileModifier }
