flowber_profile_homepage:
    path:     /{circleId}
    defaults: { _controller: FlowberProfileBundle:Profile:getUserProfile }

flowber_profile_edit:
    path:     /{circleId}/edit
    defaults: { _controller: FlowberProfileBundle:Profile:getEditProfile }

    
