flowber_user_homepage_bis:
    path:     /test2
    defaults: { _controller: FlowberUserBundle:Default:index2 }
     
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /inscription

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /nouveau_mot_de_passe

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /changer_mot_de_passe
    
flowber_registration_finishing:
    path:   /inscription-details
    defaults: { _controller: FlowberUserBundle:Registration:registrationFinalStep }