fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

flowber_user_signin_homepage:
    path: /connexion
    defaults: { _controller: FlowberUserBundle:User:getHomeConnectionPage }

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /inscription

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reinitialiser_mot_de_passe

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /changer_mot_de_passe
    
flowber_registration_finishing:
    path:   /inscription-details
    defaults: { _controller: FlowberUserBundle:Registration:registrationFinalStep }

flowber_add_friend:
    path:   /ajouter_un_ami/{id}
    defaults: { _controller: FlowberUserBundle:Friend:addFriend }

flowber_send_wink:
    path:   /envoyer_clin_oeil/{id}
    defaults: { _controller: FlowberUserBundle:Friend:sendWink }
