wybe_front_office_homepage:
    path:     /profile
    defaults: { _controller: WybeFrontOfficeBundle:Default:index }

wybe_front_office_gettest:
    path:     /hello/{name}
    defaults: { _controller: WybeFrontOfficeBundle:Default:getTest }
    
wybe_front_office_signin:
    path: /
    defaults: { _controller: WybeFrontOfficeBundle:Default:signIn }

wybe_front_office_signup_details:
    path: /signup-details/
    defaults: { _controller: WybeFrontOfficeBundle:Default:signUpDetails }