wybe_front_office_profile:
    path:     /profil
    defaults: { _controller: WybeFrontOfficeBundle:Default:index }

wybe_front_office_gettest:
    path:     /hello/{name}
    defaults: { _controller: WybeFrontOfficeBundle:Default:getTest }
    
wybe_front_office_signin:
    path: /
    defaults: { _controller: WybeFrontOfficeBundle:Default:getSignIn }

wybe_front_office_signup_details:
    path: /connexion/
    defaults: { _controller: WybeFrontOfficeBundle:Default:getSignUpDetails }
    
wybe_front_office_parameters:
    path: /parametres
    defaults: { _controller: WybeFrontOfficeBundle:Default:getParameters }
    
wybe_front_office_events:
    path: /evenements/{eventNameSlug}
    defaults: { _controller: WybeFrontOfficeBundle:Default:getEvent }

wybe_front_office_events_gallery:
    path: /evenements/{eventNameSlug}/galleries
    defaults: { _controller: WybeFrontOfficeBundle:Default:getEventGallery }

wybe_front_office_events_member:
    path: /evenements/{eventNameSlug}/participants
    defaults: { _controller: WybeFrontOfficeBundle:Default:getEventMember }

wybe_front_office_create_event:
    path: /creation_evenement
    defaults: { _controller: WybeFrontOfficeBundle:Default:getCreateEvent }
    
wybe_front_office_look_for_event:
    path: /chercher_evenement
    defaults: { _controller: WybeFrontOfficeBundle:Default:getLookForEvent }    
    
wybe_front_office_groups:
    path: /groupes/{groupNameSlug}
    defaults: { _controller: WybeFrontOfficeBundle:Default:getGroup }
    
wybe_front_office_groups_member:
    path: /groupes/{groupNameSlug}/membres
    defaults: { _controller: WybeFrontOfficeBundle:Default:getGroupMember }
    
wybe_front_office_groups_event:
    path: /groupes/{groupNameSlug}/evenements
    defaults: { _controller: WybeFrontOfficeBundle:Default:getGroupEvent }
    
wybe_front_office_groups_gallery:
    path: /groupes/{groupNameSlug}/gallery
    defaults: { _controller: WybeFrontOfficeBundle:Default:getGroupGallery }

wybe_front_office_create_group:
    path: /creation_groupe
    defaults: { _controller: WybeFrontOfficeBundle:Default:getCreateGroup }
    
wybe_front_office_look_for_group:
    path: /chercher_groupe
    defaults: { _controller: WybeFrontOfficeBundle:Default:getLookForGroup }      

wybe_front_office_notif:
    path: /notification/{notifNameSlug}
    defaults: { _controller: WybeFrontOfficeBundle:Default:getNotif }    